# -*- coding: utf-8 -*-
"""Coding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Fw1sR5ykZO3UnN6zffDZgx4pOjG9Hue
"""

def greet():
  print('Hello World!')
greet()
print('Outside function')



def greet(name):
  print('Hello,name')
greet("John")

def add_numbers(num1,num2):        #colon compulsory
  sum=num1+num2
  print("Sum:",sum)
add_numbers(5,4)

def find_square(num):
   result=num*num
   return result
square=find_square(8)
print('Square:',square)

def future_function():
  pass
future_function()

import math
square_root=math.sqrt(4)
print("Square root of 4 is",square_root)
power=pow(2,3)
print("2 to the power is 3 is",power)

def is_prime(num):
    if num <= 1:
        return False
    if num == 2:
        return True
    if num % 2 == 0:
        return False
    i = 3
    while i * i <= num:
        if num % i == 0:
            return False
        i += 2
    return True

print(f"Is 13 prime? {is_prime(13)}")
print(f"Is 4 prime? {is_prime(4)}")
print(f"Is 2 prime? {is_prime(2)}")
print(f"Is 1 prime? {is_prime(1)}")
print(f"Is 7 prime? {is_prime(7)}")

def add_numbers(a,b):
  sum=a+b
  print('Sum:',sum)
  add_numbers(2,3)

#Nested loop
def outer(x):
  def inner(y):
    return x+y
  return inner
add_five=outer(5)
result=add_five(6)
print(result)

class Dog:
  def init_self():
    pass

ozzy=Dog()

class Dog:    #blueprint or template to create objects(dogs)
  def init_(self,name,age):     #self refers to the current object
    self.name=name      #attribute(variable) called name
    self.age=age   #2nd object

class Dog:
  def __init__(self,name,age):
    self.name=name
    self.age=age
ozzy=Dog("Ozzy",2)
print(ozzy.name)
print(ozzy.age)
print(ozzy.name+"is"+str(ozzy.age)+"years old.")

class Dog:
    def init_(self,name,age):     #self refers to the current object
      self.name=name
      self.age=age

    def bark(self):
      print("bark,bark!")

    def doginfo(self):
      print(self.name + "is" +str(self.age)+ "years old.")
ozzy=Dog("Ozzy", 2)
skippy=Dog("Skippy", 12)
filou=Dog("Filou", 8)

ozzy.doginfo()
skippy.doginfo()
filou.doginfo()

class Dog:
      def __init__(self,name,age):     #self refers to the current object
          self.name=name
          self.age=age
      def bark(self):
          print("bark bark!")
      def doginfo(self):
          print(self.name + " is " + str(self.age) + " year(s) old.")
      def birthday(self):
          self.age+=1
ozzy=Dog("Ozzy", 2)
print (ozzy.age)

from os import name
class Dog:
  def __init__(self,name,age):
    self.name=name
    self.age=age

  def bark(self):
      print("bark bark!")

  def doginfo(self):
        print(self.name + "is" +str(self.age + "years old."))

  def birthday(self):
        self.age+=1

  def setBuddy(self,buddy):
      self.buddy=buddy
      buddy.buddy=self

import pandas as pd

import yfinance as yf

aapl = yf.download("AAPL", start="2020-01-01", end="2023-01-01")

import pandas as pd
import yfinance as yf

# Download Apple stock data
aapl = yf.download("AAPL", start="2020-01-01", end="2023-01-01")

short_window = 40
long_window = 100

signals = pd.DataFrame(index=aapl.index)
signals['signal'] = 0.0

signals['short_mavg'] = aapl['Close'].rolling(window=short_window, min_periods=1).mean()
signals['long_mavg'] = aapl['Close'].rolling(window=long_window, min_periods=1).mean()

signals['positions'] = signals['signal'].diff()

print(signals)

short_window=40
long_window=100
signals=pd.DataFrame(index=aapl.index)
signals['signal']=0.0

signals['short_mavg']=aapl['Close'].rolling(window=short_window,min_periods=1,center=False).mean()
signals['long_mavg']=aapl['Close'].rolling(window=long_window,min_periods=1,center=False).mean()
signals['positions']=signals['signal'].diff()
print(signals)



class Dog:
  def __init__(self,name,breed):
    self.name=name
    self.breed=breed

class Dog:
  def __init__(self,name,breed,owner):
    self.name=name
    self.breed=breed
    self.owner=owner
  def bark(self):
        print("Woof woof!")

class Owner:
  def __init__(self,name,address,contact_number):
    self.name=name
    self.address=address
    self.contact_number=contact_number
owner1=Owner("Alice Smith","456 Elm St","555-5678")
dog1= Dog("Bruce","Scooty", owner1)
print(dog1.owner.name)
dog1.bark()

print(dog1.name)
print(dog1.breed)
owner2=Owner("John Doe","123 Main St","555-1234")    #object is the instance of the class
dog2=Dog("Max","Golden Retriever", owner2)
print(dog2.owner.name)
dog2.bark()
print(dog2.name)
print(dog2.breed)

class Person:
  def __init__(self,name,age):
    self.name=name   #current specific object
    self.age=age

  def greet(self):
    print(f"Hello,my name is {self.name} and I am {self.age} years old.")
  person1=Person("Alice",30)
  person1.greet
  person2=Person("Bob",25)
  person2.greet

class User:
    def __init__(self, name, email,password):
        self.name = name
        self.email = email

    def say_hi_to_user(self,user):
        print(f"Sending message to {user.username}:Hi{user.username},it's {self.username}")
user1=User("Danny","danny@gmail.com","123")
print(user1.email)
user1.email=danny@gmail.com
print(user1.email)
user2=User("John","john@gmail.com","456")

class User:
  def __init__(self,username,email,password):       #constructor
    self.username= username
    self.email=email # Changed from _email to email for consistency with access below
    self.password=password

user1=User("dantheman","dantheman@gmail.com","123")
print(user1.email)
user1.email="dan"
print(user1.email)

class User:
  def __init__(self,username,email,password):     #takes 3 inputs
    self.username=username                    #username dantheman ,email his email will be stored
    self.email=email
  def clean_email(self):
    return self.email.lower().strip()                  #converts to lowercase, strip removes extra spaces from start to end
user1=User("dantheman","Dantheman@gmail.com","123")      #U capital class name
print(user1.email)                                        #protected variables in python
print(user1.clean_email())
user1=User("dantheman","dan@gmail.com",123)
print(user1.get_email())

import datetime # Added this import

class User:
  def __init__(self,username,email,password):
    self.username=username
    self.email=email # Consistent with usage later
    self.password=password

  def get_email(self):
    print(f"Email accessed at {datetime.datetime.now()}")
    return self.email # Changed from self._email to self.email

  def set_email(self,new_email):
    self.email=new_email # Changed from self._email to self.email

# These lines should be outside the class definition
user1=User("dantheman","dantheman@gmail.com","123")
print(user1.get_email()) # Fixed syntax error here
user1.set_email("dan@gmail.com")
print(user1.get_email())

class User:
  def __init__(self,username,email,password):    #constructor
    self.username=username                        #attributes (instance variables)
    self._email=email
    self.password=password

  #@property
  #def email(self):
  #print("Email accessed ")                #always print and return on the same line check alwsys
  #return self._email



  def get_email(self):                                  #function inside class
    print(f"Email accessed at{datetime.datetime.now()}")      #this string contains variables or expressions inside {} — evaluate them and insert their values.”
    return self._email                                          #returns email back to the caller

  def set_email(self,new_email):
    if "@" in new_email:
      self._email=new_email

  user1=User("dantheman","dan@gmail.com","123")
  user1.email="this is not an email"
  print(user1.email())                                  #